x-- MySQL Script generated by MySQL Workbench
-- Mon May  6 12:11:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema transcript
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema transcript
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transcript` DEFAULT CHARACTER SET utf8 ;
USE `transcript` ;

-- -----------------------------------------------------
-- Table `transcript`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transcript`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoPaterno` VARCHAR(45) NOT NULL,
  `ApellidoMaterno` VARCHAR(45) NULL,
  `CorreoElectronico` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `AreaConocimiento` VARCHAR(45) NOT NULL,
  `GradoAcademico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `transcript`.`transcripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transcript`.`transcripcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Transcripcion` VARCHAR(10000) NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `FechaCreacion` DATE NOT NULL,
  ` UltimaModificacion` DATE NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `transcript`.`usuario_transcripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transcript`.`usuario_transcripcion` (
  `fkIdUsuario` INT NOT NULL,
  `fkIdTranscripcion` INT NOT NULL);
  
ALTER TABLE usuario_transcripcion
	ADD PRIMARY KEY(`fkIdUsuario`,`fkIdTranscripcion`),
	ADD KEY (`fkIdTranscripcion`);
	
ALTER TABLE `usuario_transcripcion`
  ADD CONSTRAINT `fk_usuario_relacion` FOREIGN KEY (`fkIdUsuario`) REFERENCES `usuario` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_transcripcion_relacion` FOREIGN KEY (`fkIdTranscripcion`) REFERENCES `transcripcion` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;